### ISSUE TITLE
compx package / automated graph layout in svgo

### ISSUE THREAD

**Issue by paultyng** [ajstarks/go-info-displays#1]
First, just wanted to say I really enjoyed your talk at Gotham Go, was one of the highlights for me!

One of the [slides](https://github.com/ajstarks/go-info-displays/blob/master/images/compx.png) caught my attention as I have been exploring some component diagram automation. It seems like this is done via the `compx` package in svgo?  Is that package just a helper around common images you may use in component diagrams?

I'm looking to write a wrapper to generate component diagrams similar to [AWS images](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/images/Case3_Diagram.png), I imagine starting with compx and modifying it would be the way to go?

In terms of layout, do you know of any good ways to automatic graph layout within the context of SVG or svgo? I imagine I could adapt algorithms from other languages if not.

**Comment by ajstarks** [comment]
You could certainly build AWS component diagrams with compx.  Before modifying it, I would first see if you can build a compx description for what you want, and then build a script to generate the description from your data.  Note that neither compx nor SVGo does any automatic layout, but you can apply the algorithm of choice by the method of your choice.

$ mklayout foo.data | compx > foo.svg  # the hypothetical mklayout reads some description 

Check out the [test file](https://github.com/ajstarks/svgo/blob/master/compx/testcomp.xml) to get a feel for your the components and the connections are structured.  (rows and columns, connections at compass points) Also check out the [built-in objects](https://github.com/ajstarks/svgo/blob/master/compx/comps.xml)
